### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by PerchunPak** [hikinight/PixelX#23]
Перед этим все было нормально, но добавил третий токен и начало выдавать ошибки через некоторое время
Переустанавливал 2 секунды назад
```
> Производится запуск [PixelX - github.com/aeonixlegit/PixelX]
(node:10892) UnhandledPromiseRejectionWarning: FetchError: request to https://pixel-dev.w84.vkforms.ru/api/data?ts=22-21 failed, reason: write EPROTO 1228:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at ClientRequest.<anonymous> (D:\PixelBot\PixelX-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
(node:10892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Для продолжения нажмите любую клавишу . . .
```

**Comment by PerchunPak** [comment]
Убрал третий токен и такая же ошибка

**Comment by PerchunPak** [comment]
Надо было впн перезапустить
