### ISSUE TITLE
Прописывает Error: Unsupported image type

### ISSUE THREAD

**Issue by listok195** [hikinight/PixelX#26]
Ссылку вставлял с двух популярных хостингов https://ru.imgbb.com/ и https://hostingkartinok.com/
Фото было в PNG, размеры 1590 на 400.
(node:13824) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C:\Users\Ленар\Desktop\PixelX-master\node_modules\canvas\lib\image.js:91:13)
    at C:\Users\Ленар\Desktop\PixelX-master\node_modules\canvas\lib\image.js:59:11
    at C:\Users\Ленар\Desktop\PixelX-master\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (C:\Users\Ленар\Desktop\PixelX-master\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (events.js:420:28)
    at PassThrough.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:13824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by listok195** [comment]
Цвета все допустимые, то есть стандартный чёрный и #D38301
