### ISSUE TITLE
бот не ставит пиксели

### ISSUE THREAD

**Issue by keyfqsY** [hikinight/PixelX#33]
![image](https://user-images.githubusercontent.com/59119998/95770559-4540de80-0cc2-11eb-8873-f8c85f81af91.png)
бот не ставит пиксели, проблема так-же появилась и у моего друга.

**Comment by keyfqsY** [comment]
![image](https://user-images.githubusercontent.com/59119998/95782046-a7f0a500-0cd7-11eb-8be7-406317149aea.png)
теперь появляются ошибки

**Comment by OxseN** [comment]
Чел можешь помочь плз? В дс
Пишет типо при запуске 
Error: Cannot find module 'C:\Windows\system32\index'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
